spring:
  application:
    name: ff-mngt
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # New database is created when app starts and destroyed when app stops
      ddl-auto: create-drop
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  datasource:
    # URL connection to database (spring-security is database name)
    url: jdbc:h2:mem:spring-security
    # H2 SQL driver dependency
    driver-class-name: org.h2.Driver
    username: root
    password: 12345
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
meal:
  cooking:
    time: 5
    count: 4
  delivery:
    time: 3
